export BROWSER=firefox
export DARCS_DONT_ESCAPE_8BIT=1
export EDITOR=vim
export PATH=~/"bin/:$PATH"
. ~/.gpg-agent-info
export GPG_AGENT_INFO
export SSH_AUTH_SOCK
export SSH_AGENT_PID
. ~/.profile.local
