#!/bin/sh
case $PACKAGE_MANAGER in
	paludis)
		what=`sed -s 's#.:.:\(.*\)-[0-9].*#\1#' /var/lib/module-rebuild/moduledb`
		echo $what
		cave resolve "$@" $what
		;;
	portage)
		emerge @module-rebuild
		;;
esac
